// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMLZIRNwLC5tal-74fWnldHhMmACHWRPo',
    appId: '1:625974158620:web:009276cc9845995e0706d9',
    messagingSenderId: '625974158620',
    projectId: 'lowgocab-2026',
    authDomain: 'lowgocab-2026.firebaseapp.com',
    storageBucket: 'lowgocab-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Xe2U5ROB8G7sZAaW4nfBa7nM9gEw8C8',
    appId: '1:625974158620:android:07b9db0ba0242e4f0706d9',
    messagingSenderId: '625974158620',
    projectId: 'lowgocab-2026',
    storageBucket: 'lowgocab-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbyJwNLAu3QhrFZKSNzCcETAXkRPfa14',
    appId: '1:625974158620:ios:b853c4bf1d0023190706d9',
    messagingSenderId: '625974158620',
    projectId: 'lowgocab-2026',
    storageBucket: 'lowgocab-2026.firebasestorage.app',
    iosBundleId: 'com.example.lowgoCab',
  );
}
